### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by vicentroca** [lucacervasio/mosesacs#1]
$ go get github.com/lucacervasio/mosesacs

package code.google.com/p/go.net/websocket: unable to detect version control system for code.google.com/ path
package code.google.com/p/go-sqlite/go1/sqlite3: unable to detect version control system for code.google.com/ path

Thanks

**Comment by lucacervasio** [comment]
hi, code.google.com has shut down few days back, i updated the imports and now seems to work. 

anyway i'm happy if someone tries moses on his bench, so if you encounter any troubles let me know and i'll be happy to help !

Luca

**Comment by vicentroca** [comment]
Thank Luca, now it works runs :)
I'm trying to implement tr-060 in my network. I configure one CPE to connecto the MosesACS but mosesACS gets an inform message, but I can't see anything in /www interface.
¿Do do I do anything with the cpe?
Thank you

**Comment by lucacervasio** [comment]
So basically you can't achieve a plain connection from cpe to acs ? 
this is supposed to work in this stage. maybe that there's some peculiarity on your cpe/network. If you can provide a pcap trace i will be happy to debug this situation.

Luca
